import { SeriesStatus } from '@prisma/client';

/**
 * Catalogue metadata for well-known series: titles, creators and genres are
 * factual reference data, the kind any library catalogue carries.
 *
 * Descriptions here are our own one-line summaries, not publisher blurbs, and
 * covers are generated by scripts/generate-covers.ts rather than sourced from
 * the publishers - see that file.
 */
export type SeedSeries = {
  slug: string;
  title: string;
  author: string;
  artist: string;
  status: SeriesStatus;
  genres: string[];
  rating: number;
  views: number;
  chapters: number;
  /** Two hues (0-360) used to generate the cover gradient. */
  hues: [number, number];
  description: string;
};

export const SERIES: SeedSeries[] = [
  {
    slug: 'solo-leveling',
    title: 'Solo Leveling',
    author: 'Chugong',
    artist: 'Dubu',
    status: SeriesStatus.COMPLETED,
    genres: ['Action', 'Fantasy', 'Adventure'],
    rating: 4.9,
    views: 5_820_000,
    chapters: 42,
    hues: [225, 275],
    description:
      'A hunter ranked at the very bottom gains the ability to grow without limit, and climbs from the weakest in the world toward the strongest.',
  },
  {
    slug: 'omniscient-readers-viewpoint',
    title: "Omniscient Reader's Viewpoint",
    author: 'Sing Shong',
    artist: 'Sleepy-C',
    status: SeriesStatus.ONGOING,
    genres: ['Action', 'Fantasy', 'Drama'],
    rating: 4.8,
    views: 4_960_000,
    chapters: 38,
    hues: [200, 250],
    description:
      'The only person who finished a long-running web novel finds its apocalypse unfolding around him, and the ending only he knows becomes his advantage.',
  },
  {
    slug: 'tower-of-god',
    title: 'Tower of God',
    author: 'SIU',
    artist: 'SIU',
    status: SeriesStatus.ONGOING,
    genres: ['Adventure', 'Fantasy', 'Mystery'],
    rating: 4.7,
    views: 4_410_000,
    chapters: 36,
    hues: [190, 230],
    description:
      'A boy enters a tower that grants any wish at its summit, chasing the one person who left him behind, floor by floor.',
  },
  {
    slug: 'the-god-of-high-school',
    title: 'The God of High School',
    author: 'Yongje Park',
    artist: 'Yongje Park',
    status: SeriesStatus.COMPLETED,
    genres: ['Action', 'Martial Arts', 'Comedy'],
    rating: 4.5,
    views: 3_780_000,
    chapters: 34,
    hues: [10, 40],
    description:
      'A martial arts tournament promising any prize to its winner turns out to be a front for something far older and far larger.',
  },
  {
    slug: 'noblesse',
    title: 'Noblesse',
    author: 'Son Jeho',
    artist: 'Lee Kwangsu',
    status: SeriesStatus.COMPLETED,
    genres: ['Action', 'Fantasy', 'Comedy'],
    rating: 4.6,
    views: 3_240_000,
    chapters: 30,
    hues: [255, 300],
    description:
      'A noble wakes after centuries of sleep and enrols in a modern high school, while older powers slowly notice he has returned.',
  },
  {
    slug: 'eleceed',
    title: 'Eleceed',
    author: 'Son Jeho',
    artist: 'ZHENA',
    status: SeriesStatus.ONGOING,
    genres: ['Action', 'Comedy', 'Fantasy'],
    rating: 4.8,
    views: 3_120_000,
    chapters: 33,
    hues: [45, 90],
    description:
      'A kind-hearted boy with unusual reflexes meets a cat carrying the mind of a world-class awakened, and gets pulled into their world.',
  },
  {
    slug: 'lookism',
    title: 'Lookism',
    author: 'Park Tae-joon',
    artist: 'Park Tae-joon',
    status: SeriesStatus.ONGOING,
    genres: ['Drama', 'Slice of Life', 'Action'],
    rating: 4.5,
    views: 2_940_000,
    chapters: 31,
    hues: [210, 195],
    description:
      'A bullied student wakes able to switch between two bodies, and learns exactly how differently the world treats each one.',
  },
  {
    slug: 'sweet-home',
    title: 'Sweet Home',
    author: 'Kim Carnby',
    artist: 'Hwang Young-chan',
    status: SeriesStatus.COMPLETED,
    genres: ['Horror', 'Thriller', 'Drama'],
    rating: 4.6,
    views: 2_610_000,
    chapters: 28,
    hues: [340, 10],
    description:
      'A withdrawn teenager moves into a run-down apartment block just as people across the city begin turning into their own worst desires.',
  },
  {
    slug: 'the-breaker',
    title: 'The Breaker',
    author: 'Jeon Geuk-jin',
    artist: 'Park Jin-hwan',
    status: SeriesStatus.COMPLETED,
    genres: ['Martial Arts', 'Action', 'Drama'],
    rating: 4.7,
    views: 2_480_000,
    chapters: 32,
    hues: [15, 350],
    description:
      'A bullied student takes a new substitute teacher as his martial arts master, without knowing what that man is running from.',
  },
  {
    slug: 'nano-machine',
    title: 'Nano Machine',
    author: 'Han-Joong Wolya',
    artist: 'Geumgangbulgoe',
    status: SeriesStatus.ONGOING,
    genres: ['Action', 'Martial Arts', 'Fantasy'],
    rating: 4.6,
    views: 2_350_000,
    chapters: 35,
    hues: [265, 220],
    description:
      'An outcast of a martial sect receives technology from a distant descendant, and rises through a world that had written him off.',
  },
  {
    slug: 'return-of-the-mount-hua-sect',
    title: 'Return of the Mount Hua Sect',
    author: 'Biga',
    artist: 'LICO',
    status: SeriesStatus.ONGOING,
    genres: ['Action', 'Martial Arts', 'Comedy'],
    rating: 4.8,
    views: 2_270_000,
    chapters: 37,
    hues: [140, 175],
    description:
      'A legendary swordsman returns a century after his death to find his once-great sect reduced to almost nothing, and sets about rebuilding it.',
  },
  {
    slug: 'wind-breaker',
    title: 'Wind Breaker',
    author: 'Jo Yongseok',
    artist: 'Jo Yongseok',
    status: SeriesStatus.COMPLETED,
    genres: ['Sports', 'Drama', 'Slice of Life'],
    rating: 4.5,
    views: 1_980_000,
    chapters: 29,
    hues: [180, 210],
    description:
      'A model student with no friends discovers competitive cycling, and finds the crew he never had on the road at night.',
  },
  {
    slug: 'weak-hero',
    title: 'Weak Hero',
    author: 'Seopass',
    artist: 'Razen',
    status: SeriesStatus.ONGOING,
    genres: ['Action', 'Drama', 'Thriller'],
    rating: 4.7,
    views: 1_840_000,
    chapters: 27,
    hues: [220, 250],
    description:
      'A small, quiet honour student survives school violence by out-thinking people far bigger than him, at a growing cost.',
  },
  {
    slug: 'study-group',
    title: 'Study Group',
    author: 'Shin Hyung-wook',
    artist: 'Shin Hyung-wook',
    status: SeriesStatus.ONGOING,
    genres: ['Action', 'Drama', 'Comedy'],
    rating: 4.6,
    views: 1_620_000,
    chapters: 26,
    hues: [30, 55],
    description:
      'A student who desperately wants to study is terrible at it and extraordinary at fighting, at a school where only the second one helps.',
  },
  {
    slug: 'true-beauty',
    title: 'True Beauty',
    author: 'Yaongyi',
    artist: 'Yaongyi',
    status: SeriesStatus.COMPLETED,
    genres: ['Romance', 'Comedy', 'Drama'],
    rating: 4.4,
    views: 1_540_000,
    chapters: 30,
    hues: [325, 350],
    description:
      'A girl who taught herself makeup from videos becomes the school beauty, and lives in fear of anyone seeing her without it.',
  },
  {
    slug: 'second-life-ranker',
    title: 'Second Life Ranker',
    author: 'Sadoyeon',
    artist: 'Nong Nong',
    status: SeriesStatus.ONGOING,
    genres: ['Action', 'Fantasy', 'Adventure'],
    rating: 4.5,
    views: 1_390_000,
    chapters: 33,
    hues: [275, 240],
    description:
      'A soldier inherits his dead twin brother place in a tower of trials, and climbs it hunting the people who killed him.',
  },
  {
    slug: 'villain-to-kill',
    title: 'Villain to Kill',
    author: 'Se Jin Bang',
    artist: 'Ko Il Kwon',
    status: SeriesStatus.ONGOING,
    genres: ['Action', 'Fantasy', 'Thriller'],
    rating: 4.4,
    views: 1_180_000,
    chapters: 25,
    hues: [285, 320],
    description:
      'A would-be hero wakes in the body of a notorious villain, and has to decide which of the two he is going to be.',
  },
  {
    slug: 'tales-of-demons-and-gods',
    title: 'Tales of Demons and Gods',
    author: 'Mad Snail',
    artist: 'Jiang Ruotai',
    status: SeriesStatus.ONGOING,
    genres: ['Action', 'Fantasy', 'Adventure'],
    rating: 4.3,
    views: 1_020_000,
    chapters: 40,
    hues: [95, 160],
    description:
      'Killed defending his city, a cultivator wakes as his teenage self with everything he learned intact, and a second chance to save it.',
  },
];
